### ISSUE TITLE
how to enlarge vm disk space

### ISSUE THREAD

**Issue by yihuang** [Gabriella439/macos-builder#1]
Thanks for the great work, but how can I enlarge the vm's disk space, so my remote building can work?

**Comment by Gabriella439** [comment]
If you clone this repository, you can use the VM to build a new copy of itself.  Specifically, use `nix run` to run the stock builder VM in one terminal window, then while it's running edit `flake.nix` and `nix build .#app` to build the successor VM.  Then stop the first VM and run `nix run` a second time to replace it with its successor.
