### ISSUE TITLE
Use Rosetta to also build x86_64 on Apple Silicon

### ISSUE THREAD

**Issue by bouk** [Gabriella439/macos-builder#5]
It would be amazing if we can use [Rosetta 2](https://xyno.space/post/nixos-utm-rosetta) inside the VM so we can also build x86_64 packages on Apple Silicon Macs

**Comment by Gabriella439** [comment]
I'm not sure to apply the guidance from that post to NixOS VMs launched by `qemu`, but I'd accept a pull request to add this if somebody knows how to do this

**Comment by bouk** [comment]
I looked into it some more and it seems QEMU doesn't support this so it would need us to create another way to run virtual machines other than QEMU, so I'll close this
